import { registerEnumType } from '@nestjs/graphql';
export enum PermissionName {
    DASHBOARD_WIEW = 'DASHBOARD_WIEW',

    CUSTOMERS_WIEW = 'CUSTOMERS_WIEW',
    CUSTOMERS_CREATE = 'CUSTOMERS_CREATE',
    CUSTOMERS_UPDATE = 'CUSTOMERS_UPDATE',
    CUSTOMERS_DELETE = 'CUSTOMERS_DELETE',

    DOCTORS_WIEW = 'DOCTORS_WIEW',
    DOCTORS_CREATE = 'DOCTORS_CREATE',
    DOCTORS_UPDATE = 'DOCTORS_UPDATE',
    DOCTORS_DELETE = 'DOCTORS_DELETE',

    REPORTS_VIEW = 'REPORTS_VIEW',
    REPORTS_CREATE = 'REPORTS_CREATE',
    REPORTS_UPDATE = 'REPORTS_UPDATE',
    REPORTS_DELETE = 'REPORTS_DELETE',

    EMAIL_NOTIFICATIONS_VIEW = 'EMAIL_NOTIFICATIONS_VIEW',
    EMAIL_NOTIFICATIONS_CREATE = 'EMAIL_NOTIFICATIONS_CREATE',
    EMAIL_NOTIFICATIONS_UPDATE = 'EMAIL_NOTIFICATIONS_UPDATE',
    EMAIL_NOTIFICATIONS_DELETE = 'EMAIL_NOTIFICATIONS_DELETE',

    SMS_NOTIFICATIONS_VIEW = 'SMS_NOTIFICATIONS_VIEW',
    SMS_NOTIFICATIONS_CREATE = 'SMS_NOTIFICATIONS_CREATE',
    SMS_NOTIFICATIONS_UPDATE = 'SMS_NOTIFICATIONS_UPDATE',
    SMS_NOTIFICATIONS_DELETE = 'SMS_NOTIFICATIONS_DELETE',

    SERVICES_VIEW = 'SERVICES_VIEW',
    SERVICES_CREATE = 'SERVICES_CREATE',
    SERVICES_UPDATE = 'SERVICES_UPDATE',
    SERVICES_DELETE = 'SERVICES_DELETE',

    COMMON_SETTINGS_VIEW = 'COMMON_SETTINGS_VIEW',
    COMMON_SETTINGS_CREATE = 'COMMON_SETTINGS_CREATE',
    COMMON_SETTINGS_UPDATE = 'COMMON_SETTINGS_UPDATE',
    COMMON_SETTINGS_DELETE = 'COMMON_SETTINGS_DELETE',

    FAQS_VIEW = 'FAQS_VIEW',
    FAQS_CREATE = 'FAQS_CREATE',
    FAQS_UPDATE = 'FAQS_UPDATE',
    FAQS_DELETE = 'FAQS_DELETE',

    TERMS_AND_CONDITIONS_VIEW = 'TERMS_AND_CONDITIONS_VIEW',
    TERMS_AND_CONDITIONS_UPDATE = 'TERMS_AND_CONDITIONS_UPDATE',

    HOME_PAGE_VIEW = 'HOME_PAGE_VIEW',
    HOME_PAGE_UPDATE = 'HOME_PAGE_UPDATE',

    ABOUT_US_VIEW = 'ABOUT_US_VIEW',
    ABOUT_US_UPDATE = 'ABOUT_US_UPDATE',

    USERS_VIEW = 'USERS_VIEW',
    USERS_CREATE = 'USERS_CREATE',
    USERS_UPDATE = 'USERS_UPDATE',
    USERS_DELETE = 'USERS_DELETE',
}
registerEnumType(PermissionName, { name: 'PermissionName' });
